SistemaNotificaciones/Models/Contrato.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SistemaNotificaciones.Models
{
    [Table("Contratos")]
    public class Contrato
    {
        public Contrato()
        {
            Activo = true;
        }

        [Key]
        public int Id { get; set; }

        [Required]
        public string Numero { get; set; }

        [Required]
        public DateTime FechaIncio { get; set; }

        [Required]
        public DateTime FechaFin { get; set; }

        [MaxLength(2000)]
        public string Observaciones { get; set; }

        public bool Activo { get; set; }

        [DataType(DataType.ImageUrl)]
        public string RutaArchivos { get; set; }

        public bool NotificacionEnviada { get; set; }
        public string Token { get; set; }

        public int PropiedadId { get; set; }
        public Propiedad Propiedad { get; set; }

        public int ServicioId { get; set; }
        public Servicio Servicio { get; set; }

        public int CobranzaId { get; set; }
        public Cobranza Cobranza { get; set; }
    }
}

SistemaNotificaciones/Controllers/ContratoController.cs
using SistemaNotificaciones.Bussiness;
using SistemaNotificaciones.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SistemaNotificaciones.ViewModel;
using AutoMapper;
using SistemaNotificaciones.Filters;
using System.Text;
using System.Net.Mail;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;
using System.Net.Mime;
using System.IO;

namespace SistemaNotificaciones.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ContratoController : Controller
    {

        private ContratoBusiness contratoBl = null;
        private Contexto contexto = null;
        private ServicioBussiness servicioBl = null;
        private CobranzaBusiness cobranzaBl = null;
        private PropiedadBusiness propiedadBl = null;
        private ManagerBusiness managerBl = null;
        private RenovacionBusiness renovacionBl = null;

        public ContratoController()
        {
            contexto = new Contexto();
            contratoBl = new ContratoBusiness(contexto);
            servicioBl = new ServicioBussiness(contexto);
            cobranzaBl = new CobranzaBusiness(contexto);
            propiedadBl = new PropiedadBusiness(contexto);
            managerBl = new ManagerBusiness(contexto);
            renovacionBl = new RenovacionBusiness(contexto);
        }

        public ActionResult Index()
        {
            var contratos = contratoBl.ReadAll();
            var contratoIndex = (from c in contratos
                                 select new Contrato()
                                 {
                                     Servicio = servicioBl.FindBy(x => x.Id == c.ServicioId).FirstOrDefault(),
                                     Cobranza = cobranzaBl.FindBy(x => x.Id == c.CobranzaId).FirstOrDefault(),
                                     Propiedad = propiedadBl.FindBy(x => x.Id == c.PropiedadId).FirstOrDefault()
                                 }).ToList();

            return View(contratos);
        }

        public ActionResult Nuevo()
        {
            var contrato = new ContratoVM();
            contrato.Activo = true;
            contrato.FechaIncio = DateTime.Today;
            contrato.Servicios = servicioBl.ReadAll();
            contrato.Cobranzas = cobranzaBl.ReadAll();
            contrato.Propiedades = propiedadBl.ReadAll();

            return View(contrato);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Nuevo(ContratoVM contratoVm)
        {
            var resultado = 0;
            try
            {
                if (!ModelState.IsValid)
                {
                    contratoVm.Propiedades = propiedadBl.ReadAll();
                    contratoVm.Servicios = servicioBl.ReadAll();
                    contratoVm.Cobranzas = cobranzaBl.ReadAll();
                    return View(contratoVm);
                }
                    


                var fechainicio = contratoVm.FechaIncio.ToShortDateString();
                var random = new Random().Next(1, 100);
                var contrato = new Contrato()
                {
                    Numero = contratoVm.Numero,
                    FechaIncio = contratoVm.FechaIncio,
                    Servicio = servicioBl.FindBy(x => x.Id == contratoVm.servicioId).FirstOrDefault(),
                    FechaFin = contratoVm.FechaFin,
                    Observaciones = contratoVm.Observaciones ?? string.Empty,
                    Activo = contratoVm.Activo,
                    Propiedad = propiedadBl.FindBy(x => x.Numero == contratoVm.NumeroPropiedad).FirstOrDefault(),
                    Cobranza = cobranzaBl.FindBy(x => x.Id == contratoVm.cobranzaId).FirstOrDefault(),
                    RutaArchivos = contratoVm.RutaArchivos ?? string.Empty,
                    Id = 0,
                    Token = contratoVm.FechaIncio.ToString("yyyyMMdd") + contratoVm.FechaFin.ToString("yyyyMMdd") + contratoVm.Numero + random.ToString()
                };

                resultado = contratoBl.Create(contrato);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex);
            }

            if (resultado == 1)
                return RedirectToAction("Index");
            else
                return View(contratoVm);
        }

        public ActionResult Editar(int id)
        {
            try
            {
                var contrato = contratoBl.Read(id);
                var propiedad = propiedadBl.FindBy(x => x.Id == contrato.PropiedadId).FirstOrDefault();
                ContratoVM contratoVm = new ContratoVM()
                {
                    Id = contrato.Id,
                    Activo = contrato.Activo,
                    cobranzaId = contrato.CobranzaId,
                    FechaFin = contrato.FechaFin,
                    Numero = contrato.Numero,
                    RutaArchivos = contrato.RutaArchivos,
                    servicioId = contrato.ServicioId,
                    Observaciones = contrato.Observaciones,
                    NumeroPropiedad = propiedad.Numero,
                    FechaIncio = contrato.FechaIncio,
                    Servicios = servicioBl.ReadAll(),
                    Cobranzas = cobranzaBl.ReadAll(),
                    Propiedades = propiedadBl.ReadAll(),
                };

                //var propiedad = propiedadBl.Read(int.Parse(contratoVm.NumeroPropiedad));
                ViewBag.Propietario = propiedad.Propietario;
                var manager = managerBl.Read(propiedad.IdManager);
                if (manager != null)
                    ViewBag.Manager = manager.Nombre + " " + manager.Apellidos;
                else
                    ViewBag.Manager = null;
                ViewBag.FechaInicio = String.Format("{0: yyyy-MM-dd}",contratoVm.FechaIncio);
                ViewBag.FechaFin = String.Format("{0: yyyy-MM-dd}", contratoVm.FechaFin);

                if (contratoVm != null)
                    return PartialView("EditarPartialView", contratoVm);
                else
                    return RedirectToAction("NotFound", "Exception");
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        [HttpPost]
        public JsonResult Editar(ContratoVM contratoVm)
        {
            var resultado = 0;
            try
            {
                if (!ModelState.IsValid)
                    resultado = 0;

                var propiedad = propiedadBl.FindBy(x => x.Numero == contratoVm.NumeroPropiedad).FirstOrDefault();
                var contrato = new Contrato()
                {
                    Id = contratoVm.Id,
                    FechaIncio = contratoVm.FechaIncio,
                    FechaFin = contratoVm.FechaFin,
                    ServicioId = contratoVm.servicioId,
                    Activo = contratoVm.Activo,
                    Numero = contratoVm.Numero,
                    Observaciones = contratoVm.Observaciones,
                    CobranzaId = contratoVm.cobranzaId,
                    PropiedadId = propiedad.Id
                };

                if (!ModelState.IsValid)
                    resultado = 0;

                resultado = contratoBl.Update(contrato);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex);
            }

            return Json(resultado);
        }

        public ActionResult Eliminar(int id)
        {
            try
            {
                var servicio = contratoBl.Read(id);
                if (servicio != null)
                    return PartialView("EliminarPartialView", servicio);
                else
                    return RedirectToAction("NotFound", "Exception");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [ActionName("Eliminar")]
        public JsonResult ConfirmarEliminar(int id)
        {
            try
            {
                var entity = contratoBl.Read(id);
                var resultado = contratoBl.Delete(entity.Id);
                return Json(resultado, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }


        /// <summary>
        /// Metodo que recibe la respuesta por parte del cliente si va a Renovar contrato o no
        /// </summary>
        /// <param name="token"></param>
        /// <param name="contrato"></param>
        /// <param name="respuesta"></param>
        /// <returns></returns>
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Renovar(string token, string contrato, int respuesta)
        {
            if(respuesta == 1)
            {
                var servicios = servicioBl.ReadAll();
                RenovarVM renovar = new RenovarVM();
                renovar.Token = token;
                renovar.Contrato = contrato;
                renovar.Servicios = servicios;
                renovar.ServicioId = 0;

                ViewBag.respuesta = 1;
                return View(renovar);
            }
            else
            {
                Renovacion renovacion = new Renovacion()
                {
                    ContratoId = int.Parse(contrato),
                    FechaRenovacion = DateTime.Today,
                    Renovo = false

                };
                var resultadoRenovacion = renovacionBl.Create(renovacion);
                ViewBag.respuesta = 2;
            }

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public JsonResult Renovar(string contrato)
        {
            //enviar correo de renovacino al admin del sistema

SistemaNotificaciones/Controllers/TableroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SistemaNotificaciones.Filters;
using System.Web.Mvc;
using SistemaNotificaciones.Models;
using SistemaNotificaciones.Bussiness;
using SistemaNotificaciones.ViewModel;

namespace SistemaNotificaciones.Controllers
{
    //[Authorize(Roles = "Admin, Normal")]
    [Authorize(Roles = "Admin, Normal")]
    public class TableroController : Controller
    {
        private Contexto contexto = null;
        private ContratoBusiness contratoBl = null;
        private PropiedadBusiness propiedadBl = null;
        private ServicioBussiness servicioBl = null;
        private CobranzaBusiness cobranzaBl = null;

        public TableroController()
        {
            contexto = new Contexto();
            contratoBl = new ContratoBusiness(contexto);
            propiedadBl = new PropiedadBusiness(contexto);
            servicioBl = new ServicioBussiness(contexto);
            cobranzaBl = new CobranzaBusiness(contexto);
        }
        public ActionResult Index()
        {
            List<Contrato> contratos = contratoBl.ReadAll();
            if (contratos == null)
                return View(new TableroVM());
            List<Contrato> contratosVm = (from c in contratos
                                          where c.Activo == true //&& c.NotificacionEnviada == false
                                          select new Contrato()
                                          {
                                              Id  = c.Id,
                                              Activo = c.Activo,
                                              FechaIncio = c.FechaIncio,
                                              FechaFin = c.FechaFin,
                                              Numero = c.Numero,
                                              ServicioId = c.ServicioId,
                                              CobranzaId = c.CobranzaId,
                                              PropiedadId = c.PropiedadId,
                                              Observaciones = c.Observaciones,
                                              RutaArchivos = c.RutaArchivos,
                                              Propiedad = propiedadBl.Read(c.PropiedadId),
                                              Servicio =  servicioBl.Read(c.ServicioId),
                                              Cobranza = cobranzaBl.Read(c.CobranzaId),
                                              Token = c.Token,
                                              NotificacionEnviada = c.NotificacionEnviada
                                          }).ToList();


            var tablero = new TableroVM() {
                Contratos = contratosVm,
                Activos = contratosVm.Where(x => x.Activo == true && (x.FechaFin > DateTime.Today) && (x.FechaFin.Subtract(DateTime.Today).TotalDays > 5)).Count(),
                Vencidos = contratosVm.Where(x => x.FechaFin < DateTime.Today).Count(),
                PorVencer = contratosVm.Where(x => x.FechaFin.Subtract(DateTime.Today).TotalDays <= 5 && x.FechaFin.Subtract(DateTime.Today).TotalDays > 0).Count()
            };
            //var vencer = contratosVm.Where(x => x.FechaFin.Subtract(DateTime.Today).TotalDays <= 5 && x.FechaFin.Subtract(DateTime.Today).TotalDays > 0).ToList();

            return View(tablero);
        }
    }
}

SistemaNotificaciones/Views/Contrato/EliminarPartialView.cshtml
@model SistemaNotificaciones.Models.Contrato

<div class="modal-header">
    <h4 class="modal-title" id="myModalLabel">Eliminar</h4>
</div>
<div class="modal-body">
    <div  class="form-group">
        <p>Confirmar eliminacion del contrato numero <strong>@Model.Numero</strong></p>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-danger" name="eliminar" data-id="@Model.Id">Eliminar</button>
    <button type="button" class="btn btn-default" name="cancelar" data-dismiss="modal">Cancelar</button>
</div>

<script type="text/javascript">
    (function () {
        $("button[name=eliminar]").on('click', function () {
            var idContrato = $(this).attr('data-id');
            var url = root;
            url += "Contrato/Eliminar";
            repository.asyncCall(url, "POST", { id: idContrato }, "html").done(function (result) {
                console.log(result);
                location.reload();
            });
        });
    })();
</script>

SistemaNotificaciones/Views/Contrato/EnviarNotificacion.cshtml
@model SistemaNotificaciones.ViewModel.EnviarNotificacion
@{
    ViewBag.Title = "EnviarNotificacion";
    Layout = "~/Views/Layout.cshtml";
}

<h1 class="titleSection">Envío de notificiación</h1>

@using (Html.BeginForm("EnviarNotificacion", "Contrato", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(x => x.IdContrato)
        @Html.HiddenFor(x => x.Token)
        <div class="form-group">
            @Html.LabelFor(model => model.NombrePropietario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.NombrePropietario, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroPropiedad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.NumeroPropiedad, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mensaje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Mensaje, 15,70, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", id = "FechaFin" } })
                @Html.ValidationMessageFor(model => model.Mensaje, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileAttached, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.HiddenFor(model => model.FileAttached)
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.FileAttached, new { type = "file"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Enviar" class="btn btn-success" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Cancelar", "Index", "Tablero")
</div>

SistemaNotificaciones/Views/Contrato/Index.cshtml
@model IEnumerable<SistemaNotificaciones.Models.Contrato>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout.cshtml";
}

<h1 class="titleSection">Catalago de Contratos</h1> @Html.ActionLink("Nuevo", "Nuevo", "Contrato", new { @class = "btn btn-primary" })
@if (Model.Count() > 0)
{
    <table class="table table-striped">
        <thead>
            <th>
                Numero
            </th>
            <th>
                Cliente
            </th>
            <th>
                Fecha Inicio
            </th>
            <th>
                Duracion
            </th>
            <th>
                Observaciones
            </th>
            <th>
                Imagen
            </th>
            <th>
                Tipo Cobro
            </th>
            <th></th>
        <thead>
        </thead>
        <tbody>
            @foreach (var contrato in Model)
            {
                <tr>
                    <td>
                        @contrato.Numero
                    </td>
                    <td>
                        @contrato.Propiedad.Propietario
                    </td>
                    <td>
                        @contrato.FechaIncio
                    </td>
                    <td>
                        @contrato.Servicio.Duracion @contrato.Servicio.Medicion
                    </td>
                    <td>
                        @if(contrato.Observaciones == "")
                        {
                            <span>--</span>
                        }
                        else
                        {
                            @contrato.Observaciones
                        }
                    </td>
                    <td>
                        @if(contrato.RutaArchivos == "" || contrato.RutaArchivos == null)
                        {
                            <span>No hay archivos</span>
                        }
                        else
                        {
                            <a href="@Url.Content(contrato.RutaArchivos)">Ver Imagen</a>
                        }
                        
                    </td>
                    <td>
                        @contrato.Cobranza.Nombre
                    </td>
                   
                    <td>
                        <button type="button" class="btn btn-primary" data-behavior="editar" data-id="@contrato.Id">
                            Editar
                        </button> &nbsp;
                        <button type="button" class="btn btn-danger" data-behavior="eliminar" data-id="@contrato.Id">
                            Eliminar
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Aun no hay Contratos agregados.</p>
    @Html.ActionLink("Agregar uno", "Nuevo")
}


<div class="modal fade" id="modalDialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modal-content">

        </div>
    </div>
</div>

@section scripts{
    <script src="~/scripts/validations.js"></script>
    <script type="text/javascript">
        $("button").click(function () {
            var idContrato = $(this).attr('data-id');
            var operacion = $(this).attr('data-behavior');
            var url = root;
            if (operacion == "editar")
                url += "Contrato/Editar";
            else if(operacion == "eliminar")
                url += "Contrato/Eliminar";
            repository.asyncCall(url, "GET", { id: idContrato }, "html").done(function (result) {
                $("#modal-content").empty();
                $("#modal-content").append(result);
                $("#modalDialog").modal();
            });
        });
    </script>
}

SistemaNotificaciones/Views/Contrato/Nuevo.cshtml
@model SistemaNotificaciones.ViewModel.ContratoVM

@{
    ViewBag.Title = "Nuevo";
    Layout = "~/Views/Layout.cshtml";
    var numeroPropiedades = Model.Propiedades.Select(x => x.Numero).ToList();
}

<h1 class="titleSection">Nuevo Contrato</h1>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Numero de Contrato</label>
            @*@Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaIncio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaIncio, new { htmlAttributes = new { @class = "form-control", id = "FechaInicio" } })
                @Html.ValidationMessageFor(model => model.FechaIncio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Servicio</label>
            <div class="col-md-10">
                <input type="hidden" name="servicioId" id="servicioId" value="" />
                <select id="_servicioId" class="form-control">
                    <option selected="selected" data-duracion="0" data-medicion="">Seleccione un Servicio</option>
                    @foreach (var servicio in Model.Servicios)
                    {
                        <option data-duracion="@servicio.Duracion" data-medicion="@servicio.Medicion" value="@servicio.Id">@servicio.Nombre</option>
                    }
                </select>
                @*@Html.DropDownListFor(model => model.servicioId, new SelectList(Model.Servicios, "Id", "Nombre", Model.Servicios.FirstOrDefault().Id.ToString()), "Seleccione un Servicio", new { @class = "form-control", id = "Servicio" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaFin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaFin, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", id = "FechaFin" } })
                @Html.ValidationMessageFor(model => model.FechaFin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observaciones, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observaciones, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observaciones, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Activo)
                    @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RutaArchivos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RutaArchivos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RutaArchivos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Numero de Propiedad</label>
            <div class="col-md-10">
                @Html.HiddenFor(x => x.NumeroPropiedad, new { id = "hidden"})
                @Html.EditorFor(model => model.NumeroPropiedad, new { htmlAttributes = new { @class = "form-control", id = "propiedades" } })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Propietario</label>
            <div class="col-md-10">
                <input type="text" value="" id="Propietario" disabled class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Manager</label>
            <div class="col-md-10">
                <input type="text" value="" id="Manager" disabled class="form-control" />
            </div>
        </div>

        

        <div class="form-group">
            <label class="control-label col-md-2">Cobranza</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.cobranzaId, new SelectList(Model.Cobranzas, "Id", "Nombre", Model.Cobranzas.FirstOrDefault().Id.ToString()), "Seleccione un tipo de cobranza", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancelar", "Index")
</div>


@section scripts{
    <script>
        $(function () {

            var propiedades = @Html.Raw(Json.Encode(numeroPropiedades));
            $("#propiedades").autocomplete({
                source : propiedades,
                select: function(a, b){
                    repository.asyncCall(root + "Propiedad/ObtenerPripietario", "GET", {numero : b.item.value}, "json").
                    done(function(data){
                        console.log(data.Numero);
                        $("#Propietario").val(data.Propietario);
                        $("#hidden").val(data.Numero);
                        if(data.Manager == null)
                            $("#Manager").val("N/A");
                        else
                            $("#Manager").val(data.Manager[0].Nombre + " " + data.Manager[0].Apellidos);
                    });
                    
                }
            });


            $("#FechaInicio").datepicker({ 
                dateFormat: 'yy-mm-dd',
                onSelect : function(newDate){
                    var fechaFin = $("#FechaFin").val();
                    if( fechaFin != "" || fechaFin != undefined){
                        var servicio = $("#_servicioId").find(":selected").text();
                        if(servicio != "" || servicio != undefined || servicio != null){
                            var incremento = parseInt($("#_servicioId option:selected").attr("data-duracion")); //parseInt(servicio.split(" ")[0]);
                            var fechaMoment = moment($(this).val()).format("YYYY-MM-DD");
                            var medida =  $("#_servicioId option:selected").attr("data-medicion").toLowerCase(); //servicio.split(" ")[1].toLowerCase();
                            aumentarFecha(medida, incremento, fechaMoment);
                        }
                    }
                },
                startDate : moment(new Date()).format("YYYY-MM-DD")
            });

            $("#FechaFin").datepicker({ 
                dateFormat: 'yy-mm-dd',
            }).attr('readonly', true);

            $("#_servicioId").on('change',function(){
                $("#servicioId").val($(this).find(":selected").val());
                var tiempo = $(this).find(":selected").text().split(" ");
                var fechaInicio = $("#FechaInicio").val();
                var fechaMoment = null;
                if(fechaInicio == "" || fechaInicio == undefined){
                    var fechaMoment = moment(new Date()).format("YYYY-MM-DD");
                    $("#FechaInicio").datepicker('setDate', fechaMoment);
                }
                else
                    var fechaMoment = moment(fechaInicio).format("YYYY-MM-DD");
                    
                var incremento = parseInt($(this).find(":selected").attr("data-duracion")); //parseInt(tiempo[0]);
                var medida = $(this).find(":selected").attr("data-medicion").toLowerCase(); //tiempo[1].toLowerCase();
                aumentarFecha(medida, incremento, fechaMoment);
            });

            var aumentarFecha = function(medida, incremento, fechaMoment){
                var fechaFin = null;
                if(medida.startsWith('d'))
                    fechaFin = moment(fechaMoment).add(incremento, 'days').format("YYYY-MM-DD");
                else if(medida.startsWith('s'))
                    fechaFin = moment(fechaMoment).add(incremento, 'weeks').format("YYYY-MM-DD");
                else if(medida.startsWith('m'))
                    fechaFin = moment(fechaMoment).add(incremento, 'months').format("YYYY-MM-DD");
                
                $("#FechaFin").datepicker('setDate', fechaFin);
            }
        });
    </script>
}