SistemaNotificaciones/Models/Cobranza.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaNotificaciones.Models
{
    [Table("Cobranzas")]
    public class Cobranza
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [MaxLength(100)]
        public string Nombre { get; set; }

        [MaxLength(300)]
        public string Descripcion { get; set; }
    }
}

SistemaNotificaciones/Controllers/CobranzaController.cs
using SistemaNotificaciones.Bussiness;
using SistemaNotificaciones.Filters;
using SistemaNotificaciones.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaNotificaciones.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CobranzaController : Controller
    {
        CobranzaBusiness cobranzaBl = null;
        Contexto contexto = null;

        public CobranzaController()
        {
            contexto = new Contexto();
            cobranzaBl = new CobranzaBusiness(contexto);
        }

        public ActionResult Index()
        {
            var managers = cobranzaBl.ReadAll();
            return View(managers);
        }

        public ActionResult Nuevo()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Nuevo(Cobranza cobranza)
        {
            var resultado = 0;
            try
            {
                if (!ModelState.IsValid)
                    return View(cobranza);
                resultado = cobranzaBl.Create(cobranza);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex);
            }

            if (resultado == 1)
                return RedirectToAction("Index");
            else
                return View(cobranza);
        }

        public ActionResult Editar(int id)
        {
            try
            {
                var manager = cobranzaBl.Read(id);
                if (manager != null)
                    return PartialView("EditarPartialView", manager);
                else
                    return RedirectToAction("NotFound", "Exception");
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        [HttpPost]
        public JsonResult Editar(Cobranza cobranza)
        {
            var resultado = 0;
            try
            {
                if (!ModelState.IsValid)
                    resultado = 0;

                resultado = cobranzaBl.Update(cobranza);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex);
            }

            return Json(resultado);
        }

        public ActionResult Eliminar(int id)
        {
            try
            {
                var manager = cobranzaBl.Read(id);
                if (manager != null)
                    return PartialView("EliminarPartialView", manager);
                else
                    return RedirectToAction("NotFound", "Exception");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [ActionName("Eliminar")]
        public JsonResult ConfirmarEliminar(int id)
        {
            try
            {
                var entity = cobranzaBl.Read(id);
                var resultado = cobranzaBl.Delete(entity.Id);
                return Json(resultado, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

SistemaNotificaciones/Views/Cobranza/EditarPartialView.cshtml
@model SistemaNotificaciones.Models.Cobranza

<div class="modal-header">
    <h4 class="modal-title" id="myModalLabel">Editar</h4>
</div>
<div class="modal-body">
    <form id="editar">
        <div class="form-group">
            <label>Nombre</label>
            <input type="text" class="form-control" name="nombre" id="nombre" value="@Model.Nombre" />
        </div>

        <div class="form-group">
            <label>Descripcion</label>
            <input type="text" class="form-control" name="descripcion" id="descripcion" value="@Model.Descripcion" />
        </div>
    </form>
</div>
<div class="modal-footer">
    <button class="btn btn-success" id="actualizar" data-id="@Model.Id">Actualizar</button>
    <button class="btn btn-default" data-dismiss="modal">Cancelar</button>
</div>

<script type="text/javascript">
    (function () {
        $("#editar").validate({
            rules: {
                nombre: "required",
            },
            messages: {
                nombre: "Este campo es requerido",
            },
        });

        $("#actualizar").on('click', function () {
            var result = $("#editar").valid(); //true or false
            var cobranza = {
                Id: $(this).attr('data-id'),
                Nombre: $("#nombre").val(),
                Descripcion: $("#descripcion").val(),
            };
            var url = root + "Cobranza/Editar";
            if (result) {
                repository.asyncCall(url, "POST", { cobranza: cobranza }, "json").done(function (result) {
                    location.reload();
                }).error(function () {
                    console.log("error");
                });
            }
        });
    })();



</script>

SistemaNotificaciones/Views/Cobranza/EliminarPartialView.cshtml
@model SistemaNotificaciones.Models.Cobranza

<div class="modal-header">
    <h4 class="modal-title" id="myModalLabel">Eliminar</h4>
</div>
<div class="modal-body">
    <div class="form-group">
        <p>Confirmar eliminacion del elemento <strong>@Model.Nombre</strong></p>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-danger" name="eliminar" data-id="@Model.Id">Eliminar</button>
    <button type="button" class="btn btn-default" name="cancelar" data-dismiss="modal">Cancelar</button>
</div>

<script type="text/javascript">
    (function () {
        $("button[name=eliminar]").on('click', function () {
            var idCobranza = $(this).attr('data-id');
            var url = root;
            url += "Cobranza/Eliminar";
            repository.asyncCall(url, "POST", { id: idCobranza }, "html").done(function (result) {
                console.log(result);
                location.reload();
            });
        });
    })();
</script>

SistemaNotificaciones/Views/Cobranza/Index.cshtml
@model IEnumerable<SistemaNotificaciones.Models.Cobranza>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout.cshtml";
}

<h1 class="titleSection">Catalago de Cobranza</h1> @Html.ActionLink("Nuevo", "Nuevo", "Cobranza", new { @class = "btn btn-primary" })
@if (Model.Count() > 0)
{
    <table class="table table-striped">
        <thead>
            <th>
                Nombre
            </th>
            <th>
                Descripcion
            </th>
            <th></th>
        </thead>
        <tbody>
            @foreach (var cobranza in Model)
            {
                <tr>
                    <td>
                        @cobranza.Nombre
                    </td>
                    <td>
                        @cobranza.Descripcion
                    </td>
                    <td>
                        <button type="button" class="btn btn-primary" data-behavior="editar" data-id="@cobranza.Id">
                            Editar
                        </button> &nbsp;
                        <button type="button" class="btn btn-danger" data-behavior="eliminar" data-id="@cobranza.Id">
                            Eliminar
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Aun no hay Cobranzas agregados.</p>
    @Html.ActionLink("Agregar una", "Nuevo")
}


<div class="modal fade" id="modalDialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modal-content">

        </div>
    </div>
</div>

@section scripts{
    <script src="~/scripts/validations.js"></script>
    <script type="text/javascript">
        $("button").click(function () {
            var idCobranza = $(this).attr('data-id');
            var operacion = $(this).attr('data-behavior');
            var url = root;
            if (operacion == "editar")
                url += "Cobranza/Editar";
            else if(operacion == "eliminar")
                url += "Cobranza/Eliminar";
            repository.asyncCall(url, "GET", { id: idCobranza }, "html").done(function (result) {
                $("#modal-content").empty();
                $("#modal-content").append(result);
                $("#modalDialog").modal();
            });
        });
    </script>
}

SistemaNotificaciones/Views/Cobranza/Nuevo.cshtml
@model SistemaNotificaciones.Models.Cobranza

@{
    ViewBag.Title = "Nuevo";
    Layout = "~/Views/Layout.cshtml";
}

<h2>Nuevo</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cobranza</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancelar", "Index")
</div>