SistemaNotificaciones/Models/Manager.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SistemaNotificaciones.Models
{
    public class Manager
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [MaxLength(40)]
        public string Nombre { get; set; }

        [Required]
        [MaxLength(40)]
        public string Apellidos { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        public bool EsPropietario { get; set; }
    }
}

SistemaNotificaciones/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SistemaNotificaciones.Repository;
using SistemaNotificaciones.Models;
using SistemaNotificaciones.Bussiness;
using SistemaNotificaciones.Filters;

namespace SistemaNotificaciones.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ManagerController : Controller
    {
        private ManagerBusiness managerBl = null;
        private Contexto contexto = null;

        public ManagerController()
        {
            contexto = new Contexto();
            managerBl = new ManagerBusiness(contexto);
        }

        public ActionResult Index()
        {
            var managers = managerBl.ReadAll();
            return View(managers);
        }

        public ActionResult Nuevo()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Nuevo(Manager manager)
        {
            var resultado = 0;
            try
            {
                if (!ModelState.IsValid)
                    return View(manager);
                resultado = managerBl.Create(manager);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex);
            }

            if (resultado == 1)
                return RedirectToAction("Index");
            else
                return View(manager);
        }

        public ActionResult Editar(int id)
        {
            try
            {
                var manager = managerBl.Read(id);
                if (manager != null)
                    return PartialView("EditarPartialView", manager);
                else
                    return RedirectToAction("NotFound", "Exception");
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        [HttpPost]
        public JsonResult Editar(Manager manager)
        {
            var resultado = 0;
            try
            {
                if (!ModelState.IsValid)
                    resultado = 0;

                resultado = managerBl.Update(manager);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex);
            }
            return Json(resultado);
        }

        public ActionResult Eliminar(int id)
        {
            try
            {
                var manager = managerBl.Read(id);
                if (manager != null)
                    return PartialView("EliminarPartialView", manager);
                else
                    return RedirectToAction("NotFound", "Exception");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [ActionName("Eliminar")]
        public JsonResult ConfirmarEliminar(int id)
        {
            try
            {
                var entity = managerBl.Read(id);
                var resultado = managerBl.Delete(entity.Id);
                return Json(resultado, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

SistemaNotificaciones/Views/Manager/EditarPartialView.cshtml
@model SistemaNotificaciones.Models.Manager

<div class="modal-header">
    <h4 class="modal-title" id="myModalLabel">Editar</h4>
</div>
<div class="modal-body">
    <form id="editar">
        <div class="form-group">
            <label>Nombre</label>
            <input type="text" class="form-control" name="nombre" id="nombre" value="@Model.Nombre" />
        </div>

        <div class="form-group">
            <label>Apellidos</label>
            <input type="text" class="form-control" name="apellidos" id="apellidos" value="@Model.Apellidos" />
        </div>

        <div class="form-group">
            <label>Correo Electronico</label>
            <input type="text" class="form-control" name="email" id="email" value="@Model.Email" />
        </div>
        @*<div class="form-group">
            <label>Es Propietario</label>
            <input type="checkbox" name="propietario" id="propietario" checked="@Model.EsPropietario" />
        </div>*@
    </form>
</div>
<div class="modal-footer">
    <button class="btn btn-success" id="actualizar" data-id="@Model.Id">Actualizar</button>
    <button class="btn btn-default" data-dismiss="modal">Cancelar</button>
</div>

<script type="text/javascript">
    (function () {
        $("#editar").validate({
            rules: {
                nombre: "required",
                apellidos: "required",
                email: "required"
            },
            messages: {
                nombre: "Este campo es requerido",
                apellidos: "Este campo es requerido",
                email: "Este campo es requerido"
            },
        });

        $("#actualizar").on('click', function () {
            var result = $("#editar").valid(); //true or false
            var manager = {
                Id : $(this).attr('data-id'),
                Nombre: $("#nombre").val(),
                Apellidos: $("#apellidos").val(),
                Email: $("#email").val()
            };
            var url = root + "Manager/Editar";
            if (result) {
                repository.asyncCall(url, "POST", { manager: manager }, "json").done(function (result) {
                    location.reload();
                }).error(function () {
                    console.log("error");
                });
            }
        });
    })();



</script>

SistemaNotificaciones/Views/Manager/EliminarPartialView.cshtml
@model SistemaNotificaciones.Models.Manager

<div class="modal-header">
    <h4 class="modal-title" id="myModalLabel">Eliminar</h4>
</div>
<div class="modal-body">
    <div  class="form-group">
        <p>Confirmar eliminacion del Manager <strong>@Model.Nombre @Model.Apellidos</strong></p>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-danger" name="eliminar" data-id="@Model.Id">Eliminar</button>
    <button type="button" class="btn btn-default" name="cancelar" data-dismiss="modal">Cancelar</button>
</div>

<script type="text/javascript">
    (function () {
        $("button[name=eliminar]").on('click', function () {
            var idManager = $(this).attr('data-id');
            var url = root;
            url += "Manager/Eliminar";
            repository.asyncCall(url, "POST", { id: idManager }, "html").done(function (result) {
                console.log(result);
                location.reload();
            });
        });
    })();
</script>

SistemaNotificaciones/Views/Manager/Index.cshtml
@model IEnumerable<SistemaNotificaciones.Models.Manager>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout.cshtml";
}

<h1 class="titleSection">Catalago de Managers</h1> @Html.ActionLink("Nuevo", "Nuevo", "Manager", new { @class = "btn btn-primary" })
@if (Model.Count() > 0)
{
    <table class="table table-striped">
        <thead>
            <th>
                Nombre
            </th>
            <th>
                Correo Electronico
            </th>
            <th></th>
        </thead>
        <tbody>
            @foreach (var manager in Model)
            {
                <tr>
                    <td>
                        @manager.Nombre @manager.Apellidos
                    </td>
                    <td>
                        @manager.Email
                    </td>
                    <td>
                        <button type="button" class="btn btn-primary" data-behavior="editar" data-id="@manager.Id">
                            Editar
                        </button> &nbsp;
                        <button type="button" class="btn btn-danger" data-behavior="eliminar" data-id="@manager.Id">
                            Eliminar
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Aun no hay Managers agregados.</p>
    @Html.ActionLink("Agregar uno", "Nuevo")
}


<div class="modal fade" id="modalDialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modal-content">

        </div>
    </div>
</div>

@section scripts{
    <script src="~/scripts/validations.js"></script>
    <script type="text/javascript">
        $("button").click(function () {
            var idManager = $(this).attr('data-id');
            var operacion = $(this).attr('data-behavior');
            var url = root;
            if (operacion == "editar")
                url += "Manager/Editar";
            else if(operacion == "eliminar")
                url += "Manager/Eliminar";
            repository.asyncCall(url, "GET", { id: idManager }, "html").done(function (result) {
                $("#modal-content").empty();
                $("#modal-content").append(result);
                $("#modalDialog").modal();
            });
        });
    </script>
}

SistemaNotificaciones/Views/Manager/Nuevo.cshtml
@model SistemaNotificaciones.Models.Manager

@{
    ViewBag.Title = "Nuevo";
    Layout = "~/Views/Layout.cshtml";
}

<h1 class="titleSection">Agregar Manager</h1>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.EsPropietario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.EsPropietario)
                    @Html.ValidationMessageFor(model => model.EsPropietario, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>