SistemaNotificaciones/Controllers/SecurityController.cs
using System.Web.Mvc;
using SistemaNotificaciones.ViewModel;
using Microsoft.AspNet.Identity;
using System.Net;
using Microsoft.Owin;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using SistemaNotificaciones.Models;
using System.Web;
using System.Linq;
using System;
using SistemaNotificaciones.Filters;

namespace SistemaNotificaciones.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SecurityController : Controller
    {
        private Contexto contexto = null;
        private UserStore<UsuarioSistema> _userStore = null;
        private UserStore<UsuarioSistema> userStore
        {
            get
            {
                if (contexto == null)
                    contexto = new Contexto();
                if (_userStore == null)
                    _userStore = new UserStore<UsuarioSistema>(contexto);

                return _userStore;
            }
        }

        private UserManager<UsuarioSistema> _userManager = null;
        public UserManager<UsuarioSistema> userManager
        {
            get
            {
                if (_userManager == null)
                    _userManager = new UserManager<UsuarioSistema>(userStore);

                return _userManager;
            }
        }

        private SignInManager<UsuarioSistema, string> _signInManager = null;
        private SignInManager<UsuarioSistema, string> signInManager
        {
            get
            {
                if (_signInManager == null)
                    _signInManager = new SignInManager<UsuarioSistema, string>(userManager, HttpContext.GetOwinContext().Authentication);

                return _signInManager;
            }
        }

        public SecurityController()
        {
            contexto = new Contexto();
        }


        public ActionResult Index()
        {
            var users = userManager.Users.ToList();
            return View(users);
        }

        [AllowAnonymous]
        public ActionResult LogIn()
        {
            var a = HttpContext.User.Identity.IsAuthenticated;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult LogIn(LoginVM login)
        {
            if (!ModelState.IsValid)
                return View(login);

            var user = userManager.FindByEmail(login.Email);
            if (user == null)
            {
                ModelState.AddModelError("", "El usuario no existe");
                return View(login);
            }
                

            var resultSignIn = signInManager.PasswordSignIn(login.Email, login.Passowrd, false, false);
            if (resultSignIn == SignInStatus.Success)
                return RedirectToAction("Index", "Tablero");
            else
            {
                ModelState.AddModelError("", "Intento de entrada incorrecto, favor de revisar su usaurio y contrasena");
                return View(login);
            }
                

        }

        [AllowAnonymous]
        public ActionResult SignOut()
        {
            if(User.Identity.IsAuthenticated)
                signInManager.AuthenticationManager.SignOut();
            return RedirectToAction("Index", "Tablero");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Nuevo()
        {
            var roles = contexto.Roles.ToList() ;

            NuevoUsuario nuevo = new NuevoUsuario()
            {
                Roles = roles
            };
            return View(nuevo);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Nuevo(SistemaNotificaciones.ViewModel.NuevoUsuario usuario)
        {
            if (!ModelState.IsValid)
                return View(usuario);

            var existUser = userManager.FindByEmail(usuario.Email) == null ? false : true;

            if (existUser)
            {
                ModelState.AddModelError("", "El usuario ya esta registrado");
                return View(usuario);
            }

            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(contexto));
            var role = roleManager.FindById(usuario.RoleId.ToString());


            var usuarioSistema = new UsuarioSistema() { UserName = usuario.Email, Email = usuario.Email };
            var createdUser = userManager.Create(usuarioSistema, usuario.Password);
            if (createdUser.Succeeded)
            {
                userManager.AddToRole(usuarioSistema.Id, role.Name);
                signInManager.SignIn(usuarioSistema, false, false);
                return RedirectToAction("Index", "Tablero");
            }
            else
                return View(usuario);
        }

        public ActionResult Eliminar(string id)
        {
            var usuario = userManager.FindById(id);
            if(usuario == null)
            {
                ModelState.AddModelError("", "El usuario a eliminar no existe");
                return RedirectToAction("Index");
            }


            return View(usuario);
        }

        [HttpPost]
        [ActionName("Eliminar")]
        public ActionResult ConfirmarEliminar(string id)
        {
            var usuario = userManager.FindById(id);
            try
            {
                userManager.Delete(usuario);
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            
            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        public ActionResult NoAutorizado(string returnUrl)
        {
            Response.StatusCode = 403;
            //ViewBag.returnUrl = returnUrl;
            return View();
        }
    }
}

SistemaNotificaciones/Views/Security/Eliminar.cshtml
@model   SistemaNotificaciones.Models.UsuarioSistema
@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Layout.cshtml";
}

<h2>Eliminar</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <h3>Confirmar que deseas Eliminar al usuario @Model.Email</h3>
    @Html.HiddenFor(x => x.Id);

    <input type="submit" value="Confirmar" class="btn btn-danger" />
}

@Html.ActionLink("Cancelar", "Index", new { @class = "btn btn-default"})

SistemaNotificaciones/Views/Security/Index.cshtml
@model IEnumerable<SistemaNotificaciones.Models.UsuarioSistema>
@using Microsoft.AspNet.Identity;
@using SistemaNotificaciones.Controllers;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout.cshtml";
}

<h2>Usuarios</h2>

@Html.ActionLink("Agregar usuario", "Nuevo", "Security")

@Html.ValidationSummary(true, "", new { @class = "text-danger" })

<ul>
    @{var security = new SecurityController(); }
    @foreach (var user in Model)
    {
        var role = security.userManager.GetRoles(user.Id).First();
        <li>@user.Email (@role) | @Html.ActionLink("Eliminar", "Eliminar", new { id = @user.Id})</li>
    }
</ul>

SistemaNotificaciones/Views/Security/LogIn.cshtml
@model SistemaNotificaciones.ViewModel.LoginVM
@{
    ViewBag.Title = "LogIn";
    Layout = "~/Views/LoginTemplate.cshtml";
}
@if (HttpContext.Current.User.Identity.IsAuthenticated)
{
    <h3>usted no esta autorizado para ver esta página</h3>
}
else
{
    <h2>LogIn</h2>
    using (Html.BeginForm())
    {
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(x => x.Email, new { @class = "control-label" })
                @Html.EditorFor(x => x.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Passowrd, new { @class = "control-label" })
                @Html.EditorFor(x => x.Passowrd, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Passowrd, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <input type="submit" value="Ingresar" class="btn btn-default" />
            </div>
        </div>
    }
}

SistemaNotificaciones/Views/Security/NoAutorizado.cshtml
@{
    ViewBag.Title = "NoAutorizado";
    Layout = "~/Views/Layout.cshtml";
}

<h2>Usted no tiene permisos para ver esa seccion.</h2>

<input type="button" value="Regresar" onclick="window.location=@ViewBag.returnUrl" class="btn btn-primary" />

SistemaNotificaciones/Views/Security/Nuevo.cshtml
@model SistemaNotificaciones.ViewModel.NuevoUsuario
@{
    ViewBag.Title = "Nuevo";
    Layout = "~/Views/Layout.cshtml";
}

<h2>Nuevo Usuario</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(x => x.Email, new { @class = "control-label"})
            @Html.EditorFor(x => x.Email, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <label class="control-label">Rol</label>
            @Html.DropDownListFor(x => x.RoleId, new SelectList(Model.Roles, "Id", "Name", Model.Roles.FirstOrDefault().Id.ToString()), "Seleccione un rol...", new { @class = "form-control"} )
            @Html.ValidationMessageFor(x => x.RoleId, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Password, new { @class = "control-label" })
            @Html.EditorFor(x => x.Password, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Password, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.ConfirmPassword, new { @class = "control-label" })
            @Html.EditorFor(x => x.ConfirmPassword, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.ConfirmPassword, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <input type="submit" value="Crear" class="btn btn-default" />
        </div>
    </div>
}
@Html.ActionLink("Cancelar", "Index", "Tablero", new { @class = "btn btn-default" })